import os
from dotenv import load_dotenv
from app.state.schemas import (
    OrchestratorOutput,
    GeneratedFiles,
    RepairAnalysis,
    EnhancementAnalysis,
)

load_dotenv()

provider = os.environ.get("LLM_PROVIDER", "mistral").lower()

if provider == "openrouter":
    from langchain_openai import ChatOpenAI

    llm = ChatOpenAI(
        model=os.environ.get("OPENROUTER_MODEL", "anthropic/claude-3.5-sonnet"),
        api_key=os.environ.get("OPENROUTER_API_KEY"),
        base_url=os.environ.get("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1"),
        temperature=0.1,
    )
elif provider == "groq":
    from langchain_openai import ChatOpenAI

    llm = ChatOpenAI(
        model=os.environ.get("GROQ_MODEL", "llama3-70b-8192"),
        api_key=os.environ.get("GROQ_API_KEY"),
        base_url=os.environ.get("GROQ_BASE_URL", "https://api.groq.com/openai/v1"),
        temperature=0.1,
    )
else:
    from langchain_mistralai import ChatMistralAI

    llm = ChatMistralAI(
        model=os.environ.get("MISTRAL_MODEL", "mistral-small-latest"), temperature=0.1
    )

from langchain_core.output_parsers import PydanticOutputParser


import re


def create_structured_llm(pydantic_schema):
    parser = PydanticOutputParser(pydantic_object=pydantic_schema)

    class StructuredLLMWrapper:
        def invoke(self, prompt_str):
            if isinstance(prompt_str, str):
                final_prompt = (
                    prompt_str
                    + "\n\nCRITICAL: You MUST output ONLY valid JSON. Absolutely NO conversational text, NO <think> tags, and NO markdown prefixes before the JSON."
                    + "\n\n"
                    + parser.get_format_instructions()
                )
            else:
                final_prompt = prompt_str

            res = llm.invoke(final_prompt)
            content = res.content

            # Explicitly strip `<think>...</think>` tags generated by Llama 3 models
            content = re.sub(
                r"<think>.*?</think>", "", content, flags=re.DOTALL
            ).strip()

            # Sometimes LLM outputs raw strings masking JSON objects inside markdown logic.
            # Evals try fetching blocks exclusively.
            try:
                return parser.parse(content)
            except Exception as e:
                import json

                fallback = re.search(r"```json\s*(.*?)\s*```", content, re.DOTALL)
                if fallback:
                    return parser.parse(fallback.group(1))

                fallback_obj = re.search(r"\{.*\}", content, re.DOTALL)
                if fallback_obj:
                    return parser.parse(fallback_obj.group(0))
                print(f"CRITICAL PARSE ERROR on LLM Output: {res.content}")
                raise e

    return StructuredLLMWrapper()


# Setup LLM with robust string-based structured output constraints
orchestrator_llm = create_structured_llm(OrchestratorOutput)
backend_llm = create_structured_llm(GeneratedFiles)
frontend_llm = create_structured_llm(GeneratedFiles)
repair_llm = create_structured_llm(RepairAnalysis)
enhancement_llm = create_structured_llm(EnhancementAnalysis)
